-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 11:32:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myPE` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ICT-items
-- -----------------------------------------------------
-- This schema was created for a stub table
USE `myPE` ;

-- -----------------------------------------------------
-- Table `myPE`.`Rollen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myPE`.`Rollen` ;

CREATE TABLE IF NOT EXISTS `myPE`.`Rollen` (
  `rol` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myPE`.`personen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myPE`.`personen` ;

CREATE TABLE IF NOT EXISTS `myPE`.`personen` (
  `ID` INT NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `emailadres` VARCHAR(45) NOT NULL,
  `telefoonnummer` VARCHAR(45) NOT NULL,
  `klas` VARCHAR(45) NULL,
  `docentafkorting` VARCHAR(45) NULL,
  `rol` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `emailadres_UNIQUE` (`emailadres` ASC),
  INDEX `fk-persoon-rol_idx` (`rol` ASC) ,
  CONSTRAINT `fk-persoon-rol`
    FOREIGN KEY (`rol`)
    REFERENCES `myPE`.`Rollen` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myPE`.`reserveringen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myPE`.`reserveringen` ;

CREATE TABLE IF NOT EXISTS `myPE`.`reserveringen` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `persoon` INT NOT NULL,
  `inleveratum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk-res-persoon_idx` (`persoon` ASC) ,
  CONSTRAINT `fk-res-persoon`
    FOREIGN KEY (`persoon`)
    REFERENCES `myPE`.`personen` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myPE`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myPE`.`items` ;

CREATE TABLE IF NOT EXISTS `myPE`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `omschrijving` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myPE`.`reserveringsintems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myPE`.`reserveringsintems` ;

CREATE TABLE IF NOT EXISTS `myPE`.`reserveringsintems` (
  `reservering` INT NOT NULL,
  `item` INT NOT NULL,
  `aantal` INT NOT NULL,
  PRIMARY KEY (`reservering`, `item`),
  INDEX `fk-resitem-item_idx` (`item` ASC) ,
  CONSTRAINT `fk-resitem-item`
    FOREIGN KEY (`item`)
    REFERENCES `myPE`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-resitem-res`
    FOREIGN KEY (`reservering`)
    REFERENCES `myPE`.`reserveringen` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `myPE`.`Rollen`
-- -----------------------------------------------------
START TRANSACTION;
USE `myPE`;
INSERT INTO `myPE`.`Rollen` (`rol`) VALUES ('docent');
INSERT INTO `myPE`.`Rollen` (`rol`) VALUES ('student');
INSERT INTO `myPE`.`Rollen` (`rol`) VALUES ('baliemedewerker');
INSERT INTO `myPE`.`Rollen` (`rol`) VALUES ('admin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `myPE`.`personen`
-- -----------------------------------------------------
START TRANSACTION;
USE `myPE`;
INSERT INTO `myPE`.`personen` (`ID`, `voornaam`, `tussenvoegsel`, `achternaam`, `emailadres`, `telefoonnummer`, `klas`, `docentafkorting`, `rol`) VALUES (1, 'Koen', 'van', 'Veen', '550990@student.mboutrecht.nl', '0652950284', '1A', NULL, 'student');
INSERT INTO `myPE`.`personen` (`ID`, `voornaam`, `tussenvoegsel`, `achternaam`, `emailadres`, `telefoonnummer`, `klas`, `docentafkorting`, `rol`) VALUES (2, 'Hans', '', 'Odijk', 'H.Odijk@mboutrecht.nl', '0628414762', NULL, 'H. Odijk', 'docent');

COMMIT;


-- -----------------------------------------------------
-- Data for table `myPE`.`reserveringen`
-- -----------------------------------------------------
START TRANSACTION;
USE `myPE`;
INSERT INTO `myPE`.`reserveringen` (`ID`, `persoon`, `inleveratum`) VALUES (1, 1, '14082022');

COMMIT;


-- -----------------------------------------------------
-- Data for table `myPE`.`items`
-- -----------------------------------------------------
START TRANSACTION;
USE `myPE`;
INSERT INTO `myPE`.`items` (`id`, `omschrijving`) VALUES (1, 'Laptop Dell');
INSERT INTO `myPE`.`items` (`id`, `omschrijving`) VALUES (2, 'Laptop ASUS');
INSERT INTO `myPE`.`items` (`id`, `omschrijving`) VALUES (3, 'Laptop Apple');
INSERT INTO `myPE`.`items` (`id`, `omschrijving`) VALUES (4, 'Laptop Medion');

COMMIT;

